spring:
  cloud:
    function:
      definition: approveCustomer
    stream:
      kafka:
        binder:
          brokers: localhost:29092

      bindings:
        approveCustomer-in-0:
          destination : new-customer-command
        approveCustomer-out-0:
          destination: new-processed-customer
