server:
  port: 8084

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

services:
  paymentGateway:
    uri: http://localhost:8085
  customerPersistence:
    uri: http://localhost:8082
  email:
    uri: http://localhost:8085
